# Generated by Django 2.0.7 on 2018-07-22 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('onitama_game', '0002_auto_20180721_1813'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('game', 'color'), ('game', 'session')},
        ),
    ]
