# Generated by Django 2.0.6 on 2018-07-24 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onitama_game', '0003_auto_20180721_1816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='move',
            old_name='player',
            new_name='color',
        ),
    ]
