# Generated by Django 2.0.6 on 2018-07-28 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onitama_game', '0004_auto_20180724_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
