# Generated by Django 2.0.7 on 2018-08-07 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onitama_game', '0006_guestuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='start_date',
            new_name='created_on',
        ),
        migrations.AddField(
            model_name='game',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='started',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='started_on',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='onitama_game.Player'),
        ),
        migrations.AddField(
            model_name='player',
            name='username',
            field=models.CharField(default='Anonymous', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sessions.Session'),
        ),
    ]
